name: Publish to Docker Hub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and publish to Docker Hub
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: ./Dockerfile Base/Dockerfile
          push: true
          platforms: linux/amd64, linux/arm64
          tags: missemily22/multifbot:latest